# Generated by Django 3.1.1 on 2020-09-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=200)),
                ('p1_ip', models.CharField(max_length=200)),
                ('p1_choice', models.CharField(max_length=200)),
                ('p2_ip', models.CharField(max_length=200)),
                ('p2_choice', models.CharField(max_length=200)),
            ],
        ),
    ]
